# Generated by Django 4.0 on 2022-06-04 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matter',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='image',
        ),
    ]
