# Generated by Django 4.0 on 2022-11-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_remove_matter_picture_remove_professor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='first_teacher',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='name_teacher',
        ),
        migrations.RemoveField(
            model_name='students',
            name='record',
        ),
        migrations.AddField(
            model_name='students',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
