# Generated by Django 4.0 on 2022-11-05 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0009_remove_user_username'),
        ('lesson', '0003_remove_enrollment_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='classroom_id',
            new_name='classroom',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='students_id',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='lesson.students'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='users',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='consumer.user'),
        ),
    ]
