# Generated by Django 4.0 on 2022-11-09 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_rename_classroom_id_enrollment_classroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='category',
        ),
    ]
