# Generated by Django 4.0 on 2022-11-15 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0009_remove_user_username'),
        ('lesson', '0005_remove_professor_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='matter_id',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='professor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom', to='lesson.professor'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='users',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='consumer.user'),
        ),
    ]
