# Generated by Django 4.0 on 2022-12-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_remove_professor_matter_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='semester_period',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
