# Generated by Django 4.0 on 2023-01-22 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0007_enrollment_semester_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='lesson.classroom'),
        ),
    ]
