# Generated by Django 4.0 on 2022-05-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0002_alter_usertype_options_alter_usertype_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='admin status'),
        ),
    ]
