# Generated by Django 4.0 on 2022-05-23 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0003_usertype_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='is_admin',
        ),
    ]
