# Generated by Django 4.0 on 2022-05-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0007_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name=' email address'),
        ),
    ]
