# Generated by Django 4.0 on 2022-08-01 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0008_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
