# Generated by Django 4.0 on 2023-01-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0011_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='types_user',
            field=models.CharField(choices=[('E', 'Estudiante'), ('P', 'Profesor/a'), ('C', 'Coordinador')], default='E', max_length=1),
        ),
    ]
