# Generated by Django 4.0 on 2022-11-09 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config_bot',
            name='content',
        ),
    ]
