# Generated by Django 4.0 on 2022-11-20 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherbot', '0002_remove_config_bot_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config_bot',
            name='matter_id',
        ),
    ]
